apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_DB: dGVzdC1jaS1jb21wLW92ZXJmbG93
    POSTGRES_USER: Y2ktY29tcC1vdmVyZmxvdy10ZWFt
    POSTGRES_PASSWORD: YzEtYzBtcC0wdjNyZmwwdw==
    POSTGRES_HOST: MjA5LjQ2LjEyMi4xMg==
    POSTGRES_PORT: MzAwMDA=
